# Generated by Django 2.0 on 2018-02-01 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('orgao', models.CharField(max_length=50, verbose_name='Órgão expedidor')),
                ('RG', models.IntegerField(unique=True, verbose_name='RG')),
                ('telefone', models.CharField(max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('observacoes', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
    ]
