# Generated by Django 2.0 on 2018-02-01 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='RG',
            field=models.BigIntegerField(unique=True, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
